kaplancloud/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('kaplancloudaccounts.urls')),
    path('api/', include('kaplancloudapi.urls')),
    path('', include('kaplancloudapp.urls')),
]

kaplancloudapp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.projects, name='projects'),
    path('project/<uuid:uuid>', views.project, name='project'),
    path('file/<uuid:uuid>', views.editor, name='editor'),
    path('reference-file/<uuid:uuid>', views.reference_file, name='reference-file'),
    path('report/<uuid:uuid>', views.report, name='report'),
    path('project/new', views.newproject, name='newproject'),
    path('translation-memories', views.translation_memories, name='translation-memories'),
    path('translation-memory/<uuid:uuid>', views.translation_memory, name='tm'),
    path('translation-memory/<uuid:uuid>/import', views.translation_memory_import, name='tm-import'),
    path('translation-memory/new', views.newtm, name='newtm'),
]

kaplancloudapp/models.py
from django.apps import apps
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models

from kaplan import open_bilingualfile

from pathlib import Path
import logging
import shutil
import tempfile
import uuid

from .custom_storage import get_private_storage
from .thread_classes import NewFileThread, NewProjectReportThread
from .utils import get_kpp_path, get_source_file_path, \
                   get_reference_file_path

# Create your models here.

file_statuses = project_statuses = (
    (-1, 'Error'),
    (0, 'Preparing'),
    (1, 'Ready for Analysis'),
    (2, 'Analyzing'),
    (3, 'Ready for Translation'),
    (4, 'In Translation'),
    (5, 'In Review'),
    (6, 'Complete'),
    (7, 'Delivered')
)

report_statuses = (
    (0, 'Blank'),
    (1, 'Ready for Processing'),
    (2, 'Processing'),
    (3, 'Complete')
)

segment_statuses = (
    (0, 'Blank'),
    (1, 'Draft'),
    (2, 'Translated')
)


class LanguageProfile(models.Model):
    name = models.CharField(max_length=64)
    iso_code = models.CharField(max_length=10, primary_key=True)
    is_ltr = models.BooleanField(default=True)
    created_by = models.ForeignKey(get_user_model(), models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Client(models.Model):
    name = models.CharField(max_length=64)
    team = models.ManyToManyField(get_user_model(), blank=True)

    def __str__(self):
        return str(self.id) + '-' + self.name


class Termbase(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    name = models.CharField(max_length=64)
    source_language = models.ForeignKey(LanguageProfile, models.PROTECT, related_name='tb_source_language')
    target_language = models.ForeignKey(LanguageProfile, models.PROTECT, related_name='tb_target_language')
    created_by = models.ForeignKey(get_user_model(), models.SET_NULL, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)


class TBEntry(models.Model):
    source = models.TextField()
    target = models.TextField()
    termbase = models.ForeignKey(Termbase, models.CASCADE)
    created_by = models.ForeignKey(get_user_model(), models.SET_NULL, blank=True, null=True, related_name='tbentry_create')
    updated_by = models.ForeignKey(get_user_model(), models.SET_NULL, blank=True, null=True, related_name='tbentry_update')
    updated_at = models.DateTimeField(auto_now=True)


class TBEntryUpdate(models.Model):
    source = models.TextField(blank=True)
    target = models.TextField(blank=True)
    tbentry = models.ForeignKey(TBEntry, models.CASCADE)
    submitted_at = models.DateTimeField(auto_now_add=True)
    submitted_by = models.ForeignKey(get_user_model(), models.SET_NULL, blank=True, null=True)


class TranslationMemory(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    name = models.CharField(max_length=64)
    source_language = models.ForeignKey(LanguageProfile, models.PROTECT, related_name='tm_source_language')
    target_language = models.ForeignKey(LanguageProfile, models.PROTECT, related_name='tm_target_language')
    created_by = models.ForeignKey(get_user_model(), models.SET_NULL, blank=True, null=True)
    client = models.ForeignKey(Client, models.SET_NULL, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Translation memories'

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('tm', kwargs={'uuid' : self.uuid})


class TMEntry(models.Model):
    source = models.TextField()
    target = models.TextField()
    translationmemory = models.ForeignKey(TranslationMemory, models.CASCADE)
    created_by = models.ForeignKey(get_user_model(), models.SET_NULL, blank=True, null=True, related_name='tmentry_create')
    updated_by = models.ForeignKey(get_user_model(), models.SET_NULL, blank=True, null=True, related_name='tmentry_update')
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.target != '':
            tmentry_update = apps.get_model('kaplancloudapp', 'TMEntryUpdate')()
            tmentry_update.source = self.source
            tmentry_update.target = self.target
            tmentry_update.tmentry = self
            if self.updated_by:
                tmentry_update.submitted_by = self.updated_by
            elif self.created_by:
                tmentry_update.submitted_by = self.created_by
            tmentry_update.save()


class TMEntryUpdate(models.Model):
    source = models.TextField(blank=True)
    target = models.TextField(blank=True)
    tmentry = models.ForeignKey(TMEntry, models.CASCADE)
    submitted_at = models.DateTimeField(auto_now_add=True)
    submitted_by = models.ForeignKey(get_user_model(), models.SET_NULL, blank=True, null=True)


class Project(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    name = models.CharField(max_length=64)
    source_language = models.ForeignKey(LanguageProfile, models.PROTECT, related_name='source_language')
    target_language = models.ForeignKey(LanguageProfile, models.PROTECT, related_name='target_language')
    created_by = models.ForeignKey(get_user_model(), models.SET_NULL, blank=True, null=True, related_name='project_create')
    managed_by = models.ManyToManyField(get_user_model(), related_name='pm', blank=True)
    termbases = models.ManyToManyField(Termbase, blank=True)
    translationmemories = models.ManyToManyField(TranslationMemory, blank=True)
    status = models.IntegerField(choices=project_statuses, default=0)
    client = models.ForeignKey(Client, models.SET_NULL, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    directory = models.CharField(max_length=100)
    due_by = models.DateTimeField(blank=True, null=True)
    _are_all_files_submitted = models.BooleanField(default=False)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return str(self.id) + '-' + self.name

    def delete(self, *args, **kwargs):
        try:
            if settings.STORAGES['default']['BACKEND'] == 'django.core.files.storage.FileSystemStorage':
                shutil.rmtree(self.directory)
            elif settings.STORAGES['default']['BACKEND'] == 'storages.backends.s3boto3.S3Boto3Storage':
                import boto3

                session = boto3.Session(aws_access_key_id=settings.AWS_S3_ACCESS_KEY_ID,
                                        aws_secret_access_key=settings.AWS_S3_SECRET_ACCESS_KEY,
                                        region_name=settings.AWS_S3_REGION_NAME)

                s3 = session.resource('s3',
                                    endpoint_url=settings.AWS_S3_ENDPOINT_URL)

                bucket = s3.Bucket(settings.S3_PRIVATE_BUCKET_NAME)

                bucket.objects.filter(Prefix=str(Path(settings.S3_PRIVATE_BUCKET_LOCATION, self.directory))).delete()

            elif settings.STORAGES['default']['BACKEND'] == 'storages.backends.gcloud.GoogleCloudStorage':
                from google.cloud import storage

                client = storage.Client()

                bucket = storage.Bucket(client, settings.GS_PRIVATE_BUCKET_NAME)

                blobs = client.list_blobs(bucket,
                                        prefix=str(Path(settings.GS_PRIVATE_BUCKET_LOCATION, self.directory))
                                        )

                bucket.delete_blobs(list(blobs), client=client)

        except Exception as e:
            logging.error(e)

        super().delete(*args, **kwargs)

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('project', kwargs={'uuid' : self.uuid})

    def get_manifest(self):
        manifest_dict = {'title':self.name,
                         'directory': str(Path(self.directory).resolve()),
                         'source_language':self.source_language.iso,
                         'target_language':self.target_language.iso,
                        }

        return manifest_dict

    def get_status(self):
        status_dict = dict(project_statuses)
        return status_dict[self.status]

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.status == 0 and self.directory.strip() == '':
            project_directory = Path(settings.PROJECTS_DIR, str(self.uuid))
            self.directory = str(project_directory)

            self.save()

        if self.status == 1 and self._are_all_files_submitted:
            ProjectFileModel = apps.get_model('kaplancloudapp', 'ProjectFile')
            project_files = ProjectFileModel.objects.filter(project=self)
            if min([self.status == pf.status for pf in project_files]):
                ProjectReportModel = apps.get_model('kaplancloudapp',
                                                    'ProjectReport')

                new_report = ProjectReportModel()
                new_report.content = {'waitingForFileAssignment':'True'}
                #new_report.created_by = self.created_by
                new_report.project = self
                new_report.save()

                for project_file in project_files:
                    new_report.project_files.add(project_file)

                new_report.status = 1
                new_report.save()


class ProjectFile(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    name = models.TextField()
    # source_language = models.ForeignKey(LanguageProfile, models.PROTECT, related_name='source_language') # TODO: Add Projects with multiple language pairs

kaplancloudapp/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError

from .models import Client, LanguageProfile, TranslationMemory

from pathlib import Path
import tempfile

from kaplan import open_bilingualfile
from kaplan.kxliff import KXLIFF


class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True


class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result
    

class AssignLinguistForm(forms.Form):
    username = forms.CharField(max_length=128)
    override = forms.BooleanField(required=False)
    role = forms.ChoiceField(choices=((0,'Translator'),(1,'Reviewer')), initial=0, widget=forms.HiddenInput())
    file_uuids = forms.CharField(widget=forms.HiddenInput())

    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            user = get_user_model().objects.get(username=username)
            return username
        except get_user_model().DoesNotExist:
            raise ValidationError('No users found with that username')


class KPPUploadForm(forms.Form):
    package = forms.FileField(widget=forms.ClearableFileInput(attrs={'accept': ','.join(['.kpp', '.krpp'])}))


class ProjectForm(forms.Form):
    name = forms.CharField(max_length=64)
    source_language = forms.ModelChoiceField(queryset=LanguageProfile.objects.all(), to_field_name='iso_code', help_text='If you don\'t see the language you need, please create a LanguageProfile in the Admin dashboard.')
    target_language = forms.ModelChoiceField(queryset=LanguageProfile.objects.all(), to_field_name='iso_code', help_text='If you don\'t see the language you need, please create a LanguageProfile in the Admin dashboard.')
    translation_memories = forms.ChoiceField(required=False)
    client = forms.ModelChoiceField(queryset=Client.objects.all(), required=False)
    project_files = MultipleFileField(widget=MultipleFileInput(attrs={'accept':','.join(['.docx', '.json', '.kxliff', '.odp', '.ods', '.odt', '.po', '.sdlxliff', '.txt', '.xliff'])}))
    reference_files = MultipleFileField(required=False)
    due_by = forms.DateTimeField(required=False, widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))
    will_pretranslate = forms.BooleanField(label='Pretranslate from TM', required=False)

    def clean_target_language(self):
        source_language = self.cleaned_data['source_language'].iso_code
        target_language = self.cleaned_data['target_language'].iso_code
        if source_language == target_language:
            raise ValidationError('Source and target language cannot be the same.')

        return self.cleaned_data['target_language']

    def clean_translation_memories(self):
        if self.cleaned_data['translation_memories'] != '' and self.cleaned_data['translation_memories'] != '-----':
            tm = TranslationMemory.objects.get(id=self.cleaned_data['translation_memories'])
            if (tm.source_language != self.cleaned_data['source_language']
            or tm.target_language != self.cleaned_data['target_language']):
                raise ValidationError('TM language pair is different from that of the project.')
            else:
                return [tm]
        else:
            return []

    def clean_project_files(self):
        files = self.cleaned_data['project_files']

        validationerrors = []
        Path('.tmp').mkdir(exist_ok=True)
        with tempfile.TemporaryDirectory(dir='.tmp') as tmpdir:
            tmpdir_path = Path(tmpdir)

            for i, file in enumerate(files):
                path_to_file = tmpdir_path / file.name

                with open(path_to_file, 'wb') as f:
                    f.write(file.read())

                try:
                    open_bilingualfile(str(path_to_file))
                    files[i].name = 'BF-' + file.name
                except:
                    try:
                        KXLIFF.new(str(path_to_file), 'xx', 'xx')
                        files[i].name = 'MF-' + file.name
                    except:
                        validationerrors.append(ValidationError('{0} not compatible.'.format(file.name)))

        if validationerrors != []:
            raise ValidationError(validationerrors)

        return files


class SearchForm(forms.Form):
    source = forms.ModelChoiceField(queryset=LanguageProfile.objects.all(), to_field_name='iso_code', required=False)
    target = forms.ModelChoiceField(queryset=LanguageProfile.objects.all(), to_field_name='iso_code', required=False)
    client = forms.ModelChoiceField(queryset=Client.objects.all(), required=False)


class SegmentCommentForm(forms.Form):
    comment = forms.CharField(widget=forms.Textarea)


class TranslationMemoryForm(forms.Form):
    name = forms.CharField(max_length=64)
    source_language = forms.ModelChoiceField(queryset=LanguageProfile.objects.all(), to_field_name='iso_code', help_text='If you don\'t see the language you need, please create a LanguageProfile in the Admin dashboard.')
    target_language = forms.ModelChoiceField(queryset=LanguageProfile.objects.all(), to_field_name='iso_code', help_text='If you don\'t see the language you need, please create a LanguageProfile in the Admin dashboard.')
    client = forms.ModelChoiceField(queryset=Client.objects.all(), required=False)


class TranslationMemoryImportForm(forms.Form):
    source_language = forms.CharField(max_length=10, required=False, help_text='Language code')
    target_language = forms.CharField(max_length=10, required=False, help_text='Language code')
    tm_file = forms.FileField(label='TM file', widget=forms.ClearableFileInput(attrs={'accept': ','.join(['.kdb', '.tmx'])}))

    def clean_tm_file(self):
        tm_file = self.files['tm_file']

        if Path(tm_file.name).suffix.lower() not in ['.kdb', '.tmx']:
            raise ValidationError('This can only process .kdb or .tmx files.')

        return self.cleaned_data['tm_file']

kaplancloudapp/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu&display=swap" rel="stylesheet">
    {% block head %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    {% block body %}
    {% endblock %}
  </body>
</html>

kaplancloudapp/templates/index.html
{% extends "base.html" %}
{% block title %}
Kaplan Cloud
{% endblock %}
{% block body %}
<main id="dashboard">
    <div id="nav">
        <nav>
            <a id="nav-projects" {% if at_projects %}class="selected"{% endif %} href="{% url 'projects' %}">Projects</a>
            <a id="nav-tms" {% if at_tms %}class="selected"{% endif %} href="{% url 'translation-memories' %}">Translation<br/>Memories</a>
            <!---<a id="nav-tbs" class="disabled" href="#" disabled>Termbases</a>
            <a id="nav-linguists" class="disabled" href="#" disabled>Linguists</a>
            <a id="nav-clients" class="disabled" href="#" disabled>Clients</a>--->
        </nav>
        <div id="version">
          <p>v0.5.1</p>
        </div>
    </div>
    {% block div %}
    {% endblock %}
</main>
{% endblock %}

kaplancloudapp/templates/newproject.html
{% extends "index.html" %}
{% load static %}
{% block head %}
<script type="text/javascript" src="{% static 'newproject.js' %}"></script>
{% endblock %}
{% block title %}
New Project | Kaplan Cloud
{% endblock %}
{% block div %}
<form enctype="multipart/form-data" method="post">
  {% csrf_token %}
  <table>
    {{form.as_table}}
    <tr>
      <th></th>
      <td><button type="submit" name="button">Create</button></td>
    </tr>

    <input type="hidden" name="tm_link" value="{% url 'translation-memories' %}">
  </table>
</form>
{% endblock %}

kaplancloudapp/templates/newtm.html
{% extends "index.html" %}
{% block title %}
New TM | Kaplan Cloud
{% endblock %}
{% block div %}
<form enctype="multipart/form-data" method="post">
  {% csrf_token %}
  <table>
    {{form.as_table}}
    <tr>
      <th></th>
      <td><button type="submit" name="button">Create</button></td>
    </tr>
  </table>
</form>
{% endblock %}

kaplancloudapp/templates/project.html
{% extends "index.html" %}
{% load static %}
{% block head %}
<script type="text/javascript" src="{% static 'project.js' %}"></script>
{% endblock %}
{% block div %}
{% if perms.kaplancloudapp.change_project %}
<div id="assign-linguist-form" {% if form1.errors %}class="show"{% endif %}>
  <form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    <table>
      {% if form1.username.errors %}
      <tr>
        <td colspan="2">{{form1.username.errors}}</td>
      </tr>
      {% endif %}
      <tr>
        <th>{{form1.username.label_tag}}</th>
        <td>{{form1.username}}</td>
      </tr>
      <tr>
        <th></th>
        <td>{{form1.override}}<label for="{{ form1.override.id_for_label }}">Override assignments for selected files.</label></td>
      </tr>
      <tr>
        <th></th>
        <td>
          {{form1.role}}
          {{form1.file_uuids}}
        </td>
      </tr>
      <tr>
        <th></th>
        <td><button type="submit" name="button">Assign</button></td>
      </tr>
      <input type="hidden" name="task">
    </table>
  </form>
</div>
<div id="kpp-upload-form" {% if form.errors %}class="show"{% endif %}>
  <form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    <table>
      {{form.as_table}}
      <tr>
        <th></th>
        <td><button type="submit" name="button">Submit</button></td>
      </tr>
      <input type="hidden" name="task" value="import">
    </table>
  </form>
</div>
{% endif %}
<header id="header-project">
  <nav>
    <!--<a class="disabled" href="#" title="Not yet implemented">Settings</a> TODO-->
    <!--<a class="disabled" href="#" title="Not yet implemented">Archive</a> TODO-->
    {% if not user.is_authenticated %}
    <a id="login" href="{% url 'login' %}"><span class="material-icons" title="login">login</span></a>
    {% else %}
    <a id="logout" href="{% url 'logout' %}"><span class="material-icons" title="logout">logout</span></a>
    {% endif %}
  </nav>
</header>
<div id="project">
  <div>
    <h3>Files</h3>
    <table>
      <tr>
        <th><input id="checkbox-main" type="checkbox"></th>
        <th>Name</th>
        <th>Status</th>
        {% if perms.kaplancloudapp.change_project %}
        <th>Translator</th>
        <th>Reviewer</th>
        {% endif %}
        <th>Due by</th>
      </tr>
      {% for file in files %}
      <tr class="file" id="{{ file.uuid }}">
        <th><input class="checkbox" type="checkbox"></th>
        <td><a href="{% url 'editor' file.uuid %}">{{file.name}}</a></td>
        <td>{{file.get_status}}</td>
        {% if perms.kaplancloudapp.change_project %}
        <td>
          {% if file.translator %}
            {{file.translator.username}}
          {% else %}
            -
          {% endif %}
        </td>
        <td>
          {% if file.reviewer %}
            {{file.reviewer.username}}
          {% else %}
            -
          {% endif %}
        </td>
        {% endif %}
        <td>
            {% if file.due_by %}
              {{file.due_by}}
            {% elif project.due_by %}
              {{project.due_by}}
            {% else %}
              -
            {% endif %}
        </td>
      </tr>
      {% endfor %}
    </table>
  </div>
  <div>
    <h3>Reference</h3>
    <table>
      <tr>
        <th>File</th>
      </tr>
      {% for ref in reference %}
      <tr>
        <td><a href="{% url 'reference-file' ref.uuid %}" target="_blank">{{ ref.name }}</a></td>
      </tr>
      {% endfor %}
    </table>
  </div>
  <div>
    <h3>Reports</h3>
    <ul>
      {% for report in reports %}
      <li><a href="{% url 'report' report.uuid %}" target="_blank">{{report.created_at}}</a></li>
      {% endfor %}
    </ul>
  </div>
</div>
<div id="context-menu">
  <button id="context-btn-download-translation" type="button">Download Translation</button>
  {% if perms.kaplancloudapp.change_project %}
  <hr/>
  <button id="context-btn-analyze">Analyze</button>
  <button id="context-btn-export">Export</button>
  <button id="context-btn-import">Import</button>
  <hr/>
  <button id="context-btn-assign-reviewer">Assign Reviewer</button>
  <button id="context-btn-assign-translator">Assign Translator</button>
  {% endif %}
</div>
<div id="report-toast">
  <p>Your report is ready. Please refresh this page to see it listed.</p>
</div>
{% csrf_token %}
{% endblock %}

kaplancloudapp/templates/projects.html
{% extends "index.html" %}
{% load static %}
{% block head %}
<script type="text/javascript" src="{% static 'main.js' %}"></script>
{% endblock %}
{% block div %}
<header>
  <nav>
    <a {% if perms.kaplancloudapp.add_project %}href="{% url 'newproject' %}"{% else %}class="disabled"{% endif %}>Create</a>
    <!--<a class="disabled" href="#" title="Not yet implemented">Import</a> TODO-->
    {% if not user.is_authenticated %}
    <a id="login" href="{% url 'login' %}"><span class="material-icons" title="login">login</span></a>
    {% else %}
    <a id="logout" href="{% url 'logout' %}"><span class="material-icons" title="logout">logout</span></a>
    {% endif %}
  </nav>
</header>
<div id="projects">
  <div id="search-form" {% if display_form %}class="show"{% endif %}>
    <form method="get">
      <table>
        <tr>
          <th><label for="{{ form.source.id }}">Source:</label></th>
          <td>{{ form.source }}</td>
          <th><label for="{{ form.target.id }}">Target:</label></th>
          <td>{{ form.target }}</td>
          <th><label for="{{ form.client.id }}">Client:</label></th>
          <td>{{ form.client }}</td>
          <td><button type="submit" class="material-icons">search</button></td>
        </tr>
      </table>
    </form>
    <span id="search-form-toggle" class="material-icons">search</span>
  </div>
  <table>
    <tr>
      <th>Name</th>
      <th>Source Language</th>
      <th>Target Language</th>
      <th>Status</th>
      <th>Due By</th>
      <th>Client</th>
      <!--<th></th>-->
    </tr>
    {% for project in projects %}
    <tr>
      <td><a href="{% url 'project' project.uuid %}">{{project.name}}</a></td>
      <td>{{project.source_language}}</td>
      <td>{{project.target_language}}</td>
      <td>{{project.get_status}}</td>
      <td>{{project.due_by}}</td>
      <td>{{project.client.name}}</td>
      <!--<td><span class="material-icons">expand_more</span></td> TODO-->
    </tr>
    {% endfor %}
  </table>
</div>
{% endblock %}

kaplancloudapp/templates/report.html
{% extends "base.html" %}
{% block title %}
Kaplan Cloud
{% endblock %}
{% block body %}
<main>
  <table>
    <tr>
      <th>File</th>
      <th>Repetitions</th>
      <th>100%</th>
      <th>95%-99%</th>
      <th>85%-94%</th>
      <th>75%-84%</th>
      <th>50%-74%</th>
      <th>New</th>
      <th>Total</th>
    </tr>
    <tr>
      <td>Total</td>
      <td>{{ total.Repetitions }}</td>
      <td>{{ total.100 }}</td>
      <td>{{ total.95 }}</td>
      <td>{{ total.85 }}</td>
      <td>{{ total.75 }}</td>
      <td>{{ total.50 }}</td>
      <td>{{ total.New }}</td>
      <td>{{ total.Total }}</td>
    </tr>
    {% for name, report in files.items %}
    <tr>
      <td>{{ name }}</td>
      <td>{{ report.Repetitions }}</td>
      <td>{{ report.100 }}</td>
      <td>{{ report.95 }}</td>
      <td>{{ report.85 }}</td>
      <td>{{ report.75 }}</td>
      <td>{{ report.50 }}</td>
      <td>{{ report.New }}</td>
      <td>{{ report.Total }}</td>
    </tr>
    {% endfor %}
  </table>
</main>
{% endblock %}

kaplancloudapp/templates/translation-memories.html
{% extends "index.html" %}
{% load static %}
{% block head %}
<script type="text/javascript" src="{% static 'main.js' %}"></script>
{% endblock %}
{% block title %}
Translation Memories | Kaplan Cloud
{% endblock %}
{% block div %}
<header>
  <nav>
    <a {% if perms.kaplancloudapp.add_translationmemory %}href="{% url 'newtm' %}"{% else %}class="disabled"{% endif %}>Create</a>
    {% if not user.is_authenticated %}
    <a id="login" href="{% url 'login' %}"><span class="material-icons" title="login">login</span></a>
    {% else %}
    <a id="logout" href="{% url 'logout' %}"><span class="material-icons" title="logout">logout</span></a>
    {% endif %}
  </nav>
</header>
<div id="tms">
  <div id="search-form" {% if display_form %}class="show"{% endif %}>
    <form method="get">
      <table>
        <tr>
          <th><label for="{{ form.source.id }}">Source:</label></th>
          <td>{{ form.source }}</td>
          <th><label for="{{ form.target.id }}">Target:</label></th>
          <td>{{ form.target }}</td>
          <th><label for="{{ form.client.id }}">Client:</label></th>
          <td>{{ form.client }}</td>
          <td><button type="submit" class="material-icons">search</button></td>
        </tr>
      </table>
    </form>
    <span id="search-form-toggle" class="material-icons">search</span>
  </div>
  <table>
    <tr>
      <th>Name</th>
      <th>Source Language</th>
      <th>Target Language</th>
      <th>Client</th>
      <!--<th></th>-->
    </tr>
    {% for tm in tms %}
    <tr>
      <td><a href="{% url 'tm' tm.uuid %}">{{tm.name}}</a></td>
      <td>{{tm.source_language}}</td>
      <td>{{tm.target_language}}</td>
      <td>{{tm.client.name}}</td>
      <!--<td><span class="material-icons">expand_more</span></td> TODO-->
    </tr>
    {% endfor %}
  </table>
</div>
{% endblock %}